### ISSUE TITLE
Ensure we cover all our newest deployments in openfoodfacts-upptime

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-upptime#2397]
Ensure we cover all our deployments

```[tasklist]
### Tasks
- [ ] https://nutripatrol.openfoodfacts.org
- [ ] search.openfoodfacts.org and net
- [ ] facets kp net and org
- [ ] taxonomy editor net and or
- [ ] madenearme (fr and en)
- [ ] combien de sucres (fr and en)
- [x] robotoff
```

**Comment by VaiTon** [comment]
Added search and search staging in 67cef04cad69b729560e8d3aeeb51e619e3aa517

**Comment by teolemon** [comment]
@VaiTon I realize we don't cover Robotoff ?

**Comment by github-throwaway** [comment]
| Feature   | Commit Hash                                      |
|-----------|--------------------------------------------------|
| Robotoff  | f3b6fe165a50093d6d345e3dcac8c88a91c6016e         |
| Nutri-Patrol (production)<br>Taxonomy editor (pre-prod)<br>Made Near Me<br>Emballé près de chez vous<br>Combien de Sucres<br>How Much Sugar  | 48cd635420f0ef12876b1f9d560211d3f65be22e         |
| Search<br>Search (staging)  | 67cef04cad69b729560e8d3aeeb51e619e3aa517         |

**Comment by github-throwaway** [comment]
@teolemon @alexgarel 
I suspect the `$ALERT_MANAGER_BASICAUTH` secret does not work for Prometheus. Could somebody update that? Or remove Prometheus fro the monitoring? As currently it is shown as down constantly :)

**Comment by github-throwaway** [comment]
@VaiTon do you have valid Prometheus credentials? If yes then you could update the secret, so it's not shown as down all the time :)

**Comment by alexgarel** [comment]
Hum or maybe we should not put basic auth for https://prometheus.openfoodfacts.org/-/healthy

**Comment by alexgarel** [comment]
@VaiTon now https://prometheus.openfoodfacts.org/-/healthy is not protected by basic auth

**Comment by github-throwaway** [comment]
After #6598 is merged. This issue can be closed. :)
